/* // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiFxsqqoD3u42YYUnP6ODiXGdUFdybas',
    appId: '1:958810472746:web:eaf1a1189c909b954c1e53',
    messagingSenderId: '958810472746',
    projectId: 'decktech-e8aba',
    authDomain: 'decktech-e8aba.firebaseapp.com',
    storageBucket: 'decktech-e8aba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-8V2b3vDWRt9A4_FHU8bMKJzx2EFW-c',
    appId: '1:958810472746:android:f24ae2dadde613594c1e53',
    messagingSenderId: '958810472746',
    projectId: 'decktech-e8aba',
    storageBucket: 'decktech-e8aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJPfHqLLbMvY5aFLcY1q5K9ifdCTk7bOA',
    appId: '1:958810472746:ios:28236e451030255c4c1e53',
    messagingSenderId: '958810472746',
    projectId: 'decktech-e8aba',
    storageBucket: 'decktech-e8aba.appspot.com',
    iosBundleId: 'com.example.decktech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJPfHqLLbMvY5aFLcY1q5K9ifdCTk7bOA',
    appId: '1:958810472746:ios:28236e451030255c4c1e53',
    messagingSenderId: '958810472746',
    projectId: 'decktech-e8aba',
    storageBucket: 'decktech-e8aba.appspot.com',
    iosBundleId: 'com.example.decktech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEiFxsqqoD3u42YYUnP6ODiXGdUFdybas',
    appId: '1:958810472746:web:55f03a879a8872d64c1e53',
    messagingSenderId: '958810472746',
    projectId: 'decktech-e8aba',
    authDomain: 'decktech-e8aba.firebaseapp.com',
    storageBucket: 'decktech-e8aba.appspot.com',
  );

} */